<?php

namespace AppBundle\Repository;

/**
 * Exception_RelationshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Exception_RelationshipRepository extends \Doctrine\ORM\EntityRepository
{
}
