<?php

namespace AppBundle\Repository;

/**
 * Guest_GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Guest_GroupRepository extends \Doctrine\ORM\EntityRepository
{
}
