<?php

namespace AppBundle\Repository;

/**
 * Table_ListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Table_ListRepository extends \Doctrine\ORM\EntityRepository
{
}
