AppBundle\Entity\Guest:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\GuestRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        guestName:
            type: string
            length: 255
            column: Guest_name
        phoneNumber1:
            type: integer
            nullable: true
            column: Phone_number_1
        phoneNumber2:
            type: integer
            nullable: true
            column: Phone_number_2
        address1:
            type: string
            length: 255
            nullable: true
            column: Address_1
        orgID:
            type: integer
            nullable: true
            column: Org_ID
    lifecycleCallbacks: {  }
